### ISSUE TITLE
Proposed Method logic

### ISSUE THREAD

**Issue by 14thApostle** [mukheshpugal/Through_Time#2]
Constructing tree of states for each possible next moves considering the possibility of time travel in the future seems inefficient and very memory hungry.

Depending on the theory/idea of time travel followed, it is possible that you can just have a main branch simulation, and then when time travel happens split it into multiple branches at the point of divergence time. 
![image](https://user-images.githubusercontent.com/52763947/87694985-85202480-c7ac-11ea-8101-10861f3730fe.png)
                                                                                                                 - Steins;Gate
Pretty similiar to tree only, but not all nodes will have splits

Are there any possible cases where this would not be sufficient?

**Comment by mukheshpugal** [comment]
Hey Irfaan,
There are two places where this approach would fail.
### Case 1
There are a few valid cases which will not be considered if we branch only when we hit the black hole. For example, consider this situation.

- There is a single being in the whole world.
- His brain is such that when he's alone, he would never reach the black hole.
- If someone else is present with him, he might reach the black hole.

In this case, there could be a path where a being from the future influences the being in present time to get into the hole. Note that the being entering the hole in the first place is caused by the travelled being. If we branch only when someone hits the portal, we will miss this path.
> Important: If a being is alone in the world in a particular time step, he never travels through time in the next step.

### Case 2
Another reason this approach would fail is that once someone hits the portal, history has to rewritten. If rewritten, there is a chance that the being never hits the portal in the first place. So you'll have to update this by dropping a branch. This will happen back and forth resulting in an endless loop.

Feel free to continue the argument if still unclear.

**Comment by mukheshpugal** [comment]
Added explanation to readme
